kind: Deployment
apiVersion: apps/v1
metadata:
  name: oauth-deployment
  labels:
    app: oauth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oauth
  template:
    metadata:
      labels:
        app: oauth
    spec:
      containers:
        - name: oauth
          image: alejoab12/clickerclass-oauth
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "350Mi"
              cpu: "150m"
            limits:
              memory: "600Mi"
              cpu: "850m"
---
apiVersion: v1
kind: Service
metadata:
  name: oauth-service
spec:
  selector:
    app: oauth
  ports:
    - protocol: TCP
      port: 8080
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: resource-oauth
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: oauth-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50