spring:
  application:
    name: toures-balon-oauth
server:
  port: 9394
    
---
spring:
  profiles:
    active:
    - dev
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"
  instance:
    prefer-ip-address: true

gema:
  oauth:
    application-config:
      frontAngular:
        password: 123456789
        name: angular
        jwt-password: 123456789
        time-expiration: 360000
          
        
      